{% set name = "cg2at" %}

package:
  name: {{ name|lower }}
  version: {{ environ['VERSION'] }}

source:
  git_rev: "v0.9"
  git_url: https://github.com/owenvickery/cg2at

requirements:
  # build:
  #   script_env: 
  #   binary_has_prefix_files:
  #     - CG2AT
  run:
    - scipy
    - numpy
    - pathlib

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }} #{{ environ['GIT_DESCRIBE_HASH'] }} 
  script_env:
    - VERSION
    - CONDA_BLD_PATH
    - package
  noarch: generic
run:
  - python

extra:
  maintainers:
    - Owen Vickery
